### PR TITLE
Build fingerprint from latest MiUI Global

### PR DESCRIPTION
**Pull request by GeoZac**

### CODE REVIEW

**Comment by GeoZac** [comment]
@ssawrav

**Comment by saketsawrav** [comment]
This work's?Did you try?Can you confirm meanwhile I'll run a build.

**Comment by GeoZac** [comment]
I cannot try as I don't have a build capable machine.
I pulled together a magisk module to change the props but it didn't work

I referenced this from http://gerrit.aicp-rom.com/#/c/35121/1/products/hydrogen.mk. and a similar one on kenzo too

**Comment by saketsawrav** [comment]
Ohh alright,anyway so i ran a build and it didn't work,tried the libra one too,https://github.com/AICP/vendor_aicp/commit/03896cf74c121517fc1f99f3bf729670da69f38e
i'll give it a try again,with disabling force permissive selinux.

**Comment by GeoZac** [comment]
I was checking for the differences and found some occurrences of wingtech (which is Xiaomi ) in all other .mk

**Pull request merged**
